language: node_js
node_js:
- "stable"
env:
global:
 - export NODE_ENV=test
dist: trusty
addons:
    postgresql: "10.4"
services:
  - postgresql
before_script:
- psql -c 'create database senditdb_test;' -U postgres
- npm install
script:
- npm test
- npm run coverage
after_success: npm run coveralls